export enum PROPERTY_TYPE {
  HOUSE = 'HOUSE',
  FLAT = 'FLAT',
  NON_RESIDENTIAL = 'NON_RESIDENTIAL',
}

export enum CLOSET_TYPE {
  SEPARATE = 'SEPARATE',
  COMMON = 'COMMON',
}

export enum HOUSE_MATERIAL_TYPE {
  BRICK = 'BRICK',
  CINDER_BLOCK = 'CINDER_BLOCK',
  WOOD = 'WOOD',
}

export enum CITIES {
  DONETSK = 'DONETSK',
  MAKEEVKA = 'MAKEEVKA',
}

export enum DISTRICTS {
  BUDENNOVSKY = 'BUDENNOVSKY',
  VOROSHILOVSKY = 'VOROSHILOVSKY',
  KALININSKY = 'KALININSKY',
  KIEVSKY = 'KIEVSKY',
  KIROVSKY = 'KIROVSKY',
  KUIBYSHEVSKY = 'KUIBYSHEVSKY',
  LENINSKY = 'LENINSKY',
  PETROVSKY = 'PETROVSKY',
  PROLETARSKY = 'PROLETARSKY',
}

export enum TYPE_OF_DEAL {
  SALE = 'SALE',
  RENT = 'RENT',
}

export enum BUILDING_CONDITION {
  LIVING = 'LIVING',
  UNDER_REPAIR = 'UNDER_REPAIR',
  EURO = 'EURO',
}

export enum AGENT_ROLES {
  GENERAL_MANAGER = 'GENERAL_MANAGER',
  DIRECTOR = 'DIRECTOR',
  AGENT = 'AGENT',
}
